### ISSUE TITLE
feature request: print compile messages to stdout when building

### ISSUE THREAD

**Issue by magnetophon** [matthiasbeyer/nixos-scripts#112]
Is it possible to see the output of the building process of the individual pkgs when doing a system rebuild?

**Comment by matthiasbeyer** [comment]
Yes, it is disabled by default, though.

-> https://github.com/matthiasbeyer/nixos-scripts/blob/master/nix-script-switch.sh#L36

I guess this is what you mean, right?

**Comment by matthiasbeyer** [comment]
For completness: I messed up with the line:

https://github.com/matthiasbeyer/nixos-scripts/blob/master/nix-script-switch.sh#L38

**Comment by magnetophon** [comment]
OK, thanks.
Sorry for the late closing-time!   ;)
