### ISSUE TITLE
feature request: add nixpkgs in "nix-script switch"

### ISSUE THREAD

**Issue by magnetophon** [matthiasbeyer/nixos-scripts#18]
I'm guessing you thought of it already, so see this issue as a reminder:

It'd be really nice if nix-script could also keep track of the state of nixpkgs you're building with, in addition to the state of the config.

Thanks for making nixos-scripts!

**Comment by matthiasbeyer** [comment]
You're welcome.

Just to clearify: `nix-script show-commit` already shows you the commit hash of nixpkgs for the currently build generation. Is that what you want? If not, please clearify!

**Comment by magnetophon** [comment]
ah, forgot about that, tbh.
The hash I can then use to checkout from upstream, right?

That is very useful, but iiuc it won't help me if I build from a locally changed nixpkgs.
And let's face it, a lot of nixos users are also nixos developers... :)

So something like you did with the config would be ideal: create a tag in the local repo.

Ideally it would tie in with the config,(and the .dot management), so you'd have a single place to check if you want to know how you got to a certain system.

**Comment by matthiasbeyer** [comment]
I'll do this. Not sure how long it will take, though, as I'm at [tübix](tuebix.org) this weekend.

**Comment by magnetophon** [comment]
Great!   :)

Have fun at tübix!

**Comment by matthiasbeyer** [comment]
@magnetophon Please review (and maybe even test?) #62 

I hope this is appropriate. I do not have time to test atm, but I will test as well.
