### ISSUE TITLE
fatal: tag ''nixos--switch'' already exists

### ISSUE THREAD

**Issue by magnetophon** [matthiasbeyer/nixos-scripts#19]
When I do:
```
./nix-script switch -c switch -w /home/bart/nixosConfig/ -- -I nixpkgs=/home/bart/source/nixpkgs
```
I get a normal build, followed by the above error.

**Comment by matthiasbeyer** [comment]
Thanks for testing. Will look into it!

**Comment by matthiasbeyer** [comment]
magnetophon:

Could you please rerun the script:

```
./nix-script -v switch -c switch -w <your config> -- <your args>
```

(Note the additional `-v` parameter. It will turn on verbosity, so I can more clearly see what is happening on your device)

**Comment by magnetophon** [comment]
./nix-script -v switch -c switch -w /home/bart/nixosConfig/ -- -I nixpkgs=/home/bart/source/nixpkgs
[nix-script]: Verbose now
[nix-script]: Found command: 'switch'
[nix-script]: Searching for script for 'switch'
[nix-script]: Parsing args for 'switch'
[nix-script]: Calling: './nix-script-switch.sh -c switch -w /home/bart/nixosConfig/ -- -I nixpkgs=/home/bart/source/nixpkgs'
[nix-script-switch.sh]: COMMAND = switch
[nix-script-switch.sh]: WD = /home/bart/nixosConfig/
[nix-script-switch.sh]: ARGS =  -I nixpkgs=/home/bart/source/nixpkgs
[nix-script-switch.sh]: sudo nixos-rebuild switch -I nixpkgs=/home/bart/source/nixpkgs
building Nix...
building the system configuration...
updating GRUB 2 menu...
activating the configuration...
setting up /etc...
[nix-script-switch.sh]: git --git-dir=/home/bart/nixosConfig//.git --work-tree=/home/bart/nixosConfig/ tag -a 'nixos--switch'
fatal: tag ''nixos--switch'' already exists

**Comment by matthiasbeyer** [comment]
Can you please re-run with the latest `add-channel-tools` revision?

**Comment by magnetophon** [comment]
@matthiasbeyer I did
```git checkout add-channel-tools```
and then 
```
./nix-script -v switch -c switch -w /home/bart/nixosConfig/ -- -I nixpkgs=/home/bart/source/nixpkgs
[nix-script]: Verbose now
[nix-script]: Found command: 'switch'
[nix-script]: Searching for script for 'switch'
[nix-script]: Parsing args for 'switch'
[nix-script]: Calling: './nix-script-switch.sh -c switch -w /home/bart/nixosConfig/ -- -I nixpkgs=/home/bart/source/nixpkgs'
[nix-script-switch.sh]: COMMAND = switch
[nix-script-switch.sh]: WD = /home/bart/nixosConfig/
[nix-script-switch.sh]: ARGS =  -I nixpkgs=/home/bart/source/nixpkgs
[nix-script-switch.sh]: sudo nixos-rebuild switch -I nixpkgs=/home/bart/source/nixpkgs
building Nix...
building the system configuration...
updating GRUB 2 menu...
activating the configuration...
setting up /etc...
[nix-script-switch.sh]: Trying: sudo nix-env -p /nix/var/nix/profiles/system --list-generations | grep current | cut -d " " -f 2
[nix-script-switch.sh]: sudo -k succeeded
[nix-script-switch.sh]: Last generation was: 
[nix-script-switch.sh]: Tag name will be default generated : 'nixos--switch'
[nix-script-switch.sh]: git --git-dir=/home/bart/nixosConfig//.git --work-tree=/home/bart/nixosConfig/ tag -a 'nixos--switch'
fatal: tag ''nixos--switch'' already exists
```

:(

**Comment by matthiasbeyer** [comment]
Hm. Okay, thanks.

I guess I need some more information, please run:

* `ls /nix/var/nix/profiles`
* `ls /nix/var/nix/profiles/system` (if the latter shows this one)
* `sudo nix-env -p /nix/var/nix/profiles/system --list-generations`

It seems that the parsing of the current generation number fails. I think I need to rewrite this part so it matches several formats of the `--list-generations` command for `nix-env`, I'm not sure why the output format should be different on your machine... we will see...

**Comment by magnetophon** [comment]
```
ls /nix/var/nix/profiles
per-user  default-1-link  system          system-11-link  system-13-link  system-15-link  system-17-link  system-19-link  system-20-link  system-3-link  system-5-link  system-7-link  system-9-link
default   default-2-link  system-10-link  system-12-link  system-14-link  system-16-link  system-18-link  system-1-link   system-2-link   system-4-link  system-6-link  system-8-link
```
```
 ls /nix/var/nix/profiles/system
bin  fine-tune  activate  configuration-name  etc  extra-dependencies  firmware  init  init-interface-version  initrd  kernel  kernel-modules  kernel-params  nixos-version  sw  system  systemd
```
nix-env -p /nix/var/nix/profiles/system --list-generations
   1   2015-06-08 00:12:55   
   2   2015-06-08 00:31:31   
   3   2015-06-09 05:04:51   
   4   2015-06-09 08:39:34   
   5   2015-06-09 15:55:24   
   6   2015-06-09 19:02:16   
   7   2015-06-11 10:55:15   
   8   2015-06-11 12:30:08   
   9   2015-06-11 12:49:01   
  10   2015-06-11 13:23:56   
  11   2015-06-11 15:05:56   
  12   2015-06-11 19:28:30   
  13   2015-06-11 23:03:39   
  14   2015-06-11 23:12:24   
  15   2015-06-12 12:42:51   
  16   2015-06-13 09:39:02   
  17   2015-06-13 09:50:56   
  18   2015-06-13 10:14:58   
  19   2015-06-13 14:34:05   
  20   2015-06-13 22:54:42   (current)
```

Odd, that the current one is from last night.
Might that be cause I didn't actually change anything from then on?

**Comment by matthiasbeyer** [comment]
Strange that my script fails to parse your output.

Your build is from last night because if you didn't change your configurationa and did not update the channel, nix won't create a new generation, I guess.

**Comment by magnetophon** [comment]
I played around with it a bit, and found out that
```
 nix-env -p /nix/var/nix/profiles/system --list-generations | grep current | cut -d " " -f 3
```
gives me the number of the generation. (note: 3 instead of 2)

**Comment by matthiasbeyer** [comment]
This is really strange. I just ran what you've posted, and for me it works with 2 instread of 3...

I'll fix the script so it recognizes both!

**Comment by matthiasbeyer** [comment]
Ah, tell me about your `nix` version!

**Comment by magnetophon** [comment]
nixos-version
15.06.git.0d5db26M (Dingo)

**Comment by matthiasbeyer** [comment]
No, I meant the version of the package manager. `nix-env --version`!

**Comment by magnetophon** [comment]
nix-env (Nix) 1.9pre4153_b64988b

**Comment by matthiasbeyer** [comment]
ah, okay. I'm working with nix 1.8 right now... so maybe the output format has changed... I'll look into that, thanks a lot for your help by now!

**Comment by magnetophon** [comment]
does the awk version above work for you?

**Comment by matthiasbeyer** [comment]
Yes, the awk version works. If it works for you, too, please feel free to provide me a patch (you can open a PR to my PR branch, if you know how this works, feel free to do so, if not, just add a patch and push and notify me, I'll cherry-pick it then)!

**Comment by magnetophon** [comment]
OK see https://github.com/matthiasbeyer/nixos-scripts/pull/20
