### ISSUE TITLE
[update-package-def]: Support for auto-push

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/nixos-scripts#79]
We could automatically push the generated branch if the build worked.

**Comment by magnetophon** [comment]
I would love that!   :+1: 

I imagine others might want a way to turn it off as wel though...

**Comment by matthiasbeyer** [comment]
@magnetophon Thanks for the feedback. I will provide a flag in the configuration file to switch it on/off by default and a flag to override the default from the config file.
