### ISSUE TITLE
feature request: show-commit for configuration.

### ISSUE THREAD

**Issue by magnetophon** [matthiasbeyer/nixos-scripts#8]
Great work you're doing! Very handy.

Would it be possible to have a script that makes a commit of the configuration on each successful build ? (ideally separate from the user managed git.)
Then you could have another script that shows you which config the current generation has.

**Comment by matthiasbeyer** [comment]
Yep, I want such a thing too.

My proposed workflow would be something like:

```bash
sudo nixos-rebuild switch && nix-script tag-config
nix-script current-commit
<hash>
```

whereas `tag-config` creates a tag in a specific repo on the current commit, where the rebuild was build of. So, for my machines, I have my `configuration.nix` in `~/config/nixos` it should create a tag like `nixos-<current date>` or something.

The `current-commit` call then should print the commit hash where my current system is build from.

---

So far, so good. Unfortunately, I have no idea how to implement the latter. I know, though, how to implement the first command.

---

Ideas on `tag-commit`

* Required configurations for the command:
  * Tag message
  * Path where the config lives

These could be solved with params to the command, but an RC file would be much nicer, I guess.

---

Any more ideas are welcome! I guess I could takle this one in about 1 week, but I'm not sure I have enough time (and motivation) on implementing this. So PRs are really apprechiated and even if they are incomplete I possibly could (re)use the commits!

**Comment by matthiasbeyer** [comment]
@magnetophon Please check whether this issue was solved in #15 

For the record: I'm planning to release a version of this as soon as I think it is stable enough. I will submit a nix(os) package then, too.

**Comment by magnetophon** [comment]
@matthiasbeyer Yeas, works as advertised!  :D 
Thanks!  :v:

**Comment by matthiasbeyer** [comment]
Please note: I did not yet release the code in this repository (not even in v0.1). So I'd use it with care!
